---
title: "Reproducible Research: Peer Assessment 1"
output: html_document 
keep_md: true
---


## Loading and preprocessing the data
```{r loading and preprocessing, warning = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)

activity <- read.csv("activity.csv")
activity <- drop_na(activity)
activity$date <- ymd(activity$date)


```


## What is mean total number of steps taken per day?
```{r}
steps_perday <- activity %>% group_by(date) %>% summarise(total_steps = sum(steps))

g <- ggplot(steps_perday, aes(total_steps))
g + geom_histogram(binwidth = 2500) 


mean(steps_perday$total_steps)
median(steps_perday$total_steps)


```

## What is the average daily activity pattern?

```{r Daily Activity Pattern}

time_interval <- activity %>% group_by(interval) %>% summarise(interval_avg_steps = mean(steps))

ggplot(data = time_interval, aes(x = interval, y = interval_avg_steps))+
  geom_line(color = "#00AFBB", size = 2)

time_interval[which.max(time_interval$interval_avg_steps), ]$interval

```
## Imputing missing values
```{r}
activity_full <- read.csv("activity.csv")

sum(is.na(activity_full$steps))

for (i in 1:length(activity_full$steps)){
        if (is.na(activity_full$steps[i] == TRUE)){        
        activity_full$steps[i] <- time_interval$interval_avg_steps[match(activity_full$interval[i], time_interval$interval)]  
        } 
}

steps_perday2 <- activity_full %>% group_by(date) %>% summarise(total_steps = sum(steps))

g <- ggplot(steps_perday2, aes(total_steps))
g + geom_histogram(binwidth = 2500) 

mean(steps_perday2$total_steps)
median(steps_perday2$total_steps)
```


## Are there differences in activity patterns between weekdays and weekends?
